/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PrimaryButton {
    }
    interface SecondaryButton {
    }
}
declare global {
    interface HTMLPrimaryButtonElement extends Components.PrimaryButton, HTMLStencilElement {
    }
    var HTMLPrimaryButtonElement: {
        prototype: HTMLPrimaryButtonElement;
        new (): HTMLPrimaryButtonElement;
    };
    interface HTMLSecondaryButtonElement extends Components.SecondaryButton, HTMLStencilElement {
    }
    var HTMLSecondaryButtonElement: {
        prototype: HTMLSecondaryButtonElement;
        new (): HTMLSecondaryButtonElement;
    };
    interface HTMLElementTagNameMap {
        "primary-button": HTMLPrimaryButtonElement;
        "secondary-button": HTMLSecondaryButtonElement;
    }
}
declare namespace LocalJSX {
    interface PrimaryButton {
    }
    interface SecondaryButton {
    }
    interface IntrinsicElements {
        "primary-button": PrimaryButton;
        "secondary-button": SecondaryButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "primary-button": LocalJSX.PrimaryButton & JSXBase.HTMLAttributes<HTMLPrimaryButtonElement>;
            "secondary-button": LocalJSX.SecondaryButton & JSXBase.HTMLAttributes<HTMLSecondaryButtonElement>;
        }
    }
}
